// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUu0PZjvw6ib0BrKePrh0kv7BdurX08_A',
    appId: '1:537101613189:web:31ae758af2deae831411ec',
    messagingSenderId: '537101613189',
    projectId: 'jayrestro-pro',
    authDomain: 'jayrestro-pro.firebaseapp.com',
    storageBucket: 'jayrestro-pro.appspot.com',
    measurementId: 'G-H585HRKXSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTWroEXGMrpgl1N_n0VgmTfqgBiku2gY',
    appId: '1:537101613189:android:51fc1c0c3541cfa81411ec',
    messagingSenderId: '537101613189',
    projectId: 'jayrestro-pro',
    storageBucket: 'jayrestro-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLK0Mln_So49OjSuVqaspjbfm5BYSAr4Y',
    appId: '1:537101613189:ios:43afdecbc72d38d81411ec',
    messagingSenderId: '537101613189',
    projectId: 'jayrestro-pro',
    storageBucket: 'jayrestro-pro.appspot.com',
    iosBundleId: 'com.jay.tech.jtable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLK0Mln_So49OjSuVqaspjbfm5BYSAr4Y',
    appId: '1:537101613189:ios:43afdecbc72d38d81411ec',
    messagingSenderId: '537101613189',
    projectId: 'jayrestro-pro',
    storageBucket: 'jayrestro-pro.appspot.com',
    iosBundleId: 'com.jay.tech.jtable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUu0PZjvw6ib0BrKePrh0kv7BdurX08_A',
    appId: '1:537101613189:web:c3f5567012bf359c1411ec',
    messagingSenderId: '537101613189',
    projectId: 'jayrestro-pro',
    authDomain: 'jayrestro-pro.firebaseapp.com',
    storageBucket: 'jayrestro-pro.appspot.com',
    measurementId: 'G-WHF23GFNQB',
  );
}
